// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// flutter pub add firebase_core
//run the command above to install it in your library yaml file.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR26rViJXY2kKHt4vpBfKTkNNb0dBlH7s',
    appId: '1:870151273124:web:c419fdec67f7d391e20431',
    messagingSenderId: '870151273124',
    projectId: 'todoflutterapp-7bf8a',
    authDomain: 'todoflutterapp-7bf8a.firebaseapp.com',
    storageBucket: 'todoflutterapp-7bf8a.firebasestorage.app',
    measurementId: 'G-X8KP7QSNKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe0LzxAXYQgbVf1hdnl9y6mkbEGyc1p5E',
    appId: '1:870151273124:android:0b5535d379a5107ce20431',
    messagingSenderId: '870151273124',
    projectId: 'todoflutterapp-7bf8a',
    storageBucket: 'todoflutterapp-7bf8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD66IAnab38x2evUexIgyr5c2tx5Wul2ws',
    appId: '1:870151273124:ios:81b4f3de59a710fde20431',
    messagingSenderId: '870151273124',
    projectId: 'todoflutterapp-7bf8a',
    storageBucket: 'todoflutterapp-7bf8a.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD66IAnab38x2evUexIgyr5c2tx5Wul2ws',
    appId: '1:870151273124:ios:81b4f3de59a710fde20431',
    messagingSenderId: '870151273124',
    projectId: 'todoflutterapp-7bf8a',
    storageBucket: 'todoflutterapp-7bf8a.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR26rViJXY2kKHt4vpBfKTkNNb0dBlH7s',
    appId: '1:870151273124:web:4c05baad1e27b6ace20431',
    messagingSenderId: '870151273124',
    projectId: 'todoflutterapp-7bf8a',
    authDomain: 'todoflutterapp-7bf8a.firebaseapp.com',
    storageBucket: 'todoflutterapp-7bf8a.firebasestorage.app',
    measurementId: 'G-C79KQJ5Z76',
  );
}
